extends Node

enum EVENT_TYPES {MOVEMENT, DAMAGE_ATTEMPT, DAMAGE_CONFIRMED, SHOOT_TARGET, ENTITY_KILLED, TARGET_REACHED, MOUSE_CLICK, MOUSE_MOTION, SCREEN_SHAKE}
enum SHAPE_TYPES {CIRCLE, DIAMOND, SQUARE, RECTANGLE}

enum LEVELS {LOW=1, MEDIUM=2, HIGH=3}
enum ENEMY_STATES {MOVE, ATTACK}

enum TOWER_TYPES {BASE, TURRET, FLAMETHROWER, BURST_SHOOTER, ROCKET_LAUNCHER}
enum ENEMY_TYPES {NORMAL}
enum ENTITY_TYPES {PLAYER, NORMAL_ENEMY, BULLET, CELL_HOVER_OVERLAY}

enum COUNTDOWN_ACTIONS {SHOOT, ATTACK}
enum ALIGNMENTS { PLAYER, ENEMY, NEUTRAL }
