extends Node

enum EVENT_TYPES {MOVEMENT, DAMAGE_ATTEMPT, DAMAGE_CONFIRMED, SHOOT_TARGET, ENTITY_KILLED, TARGET_REACHED, MOUSE_CLICK, MOUSE_MOTION, SCREEN_SHAKE, GAME_OVER, UPGRADE_APPLIED, SAVE_REQUESTED, SHOW_DEATH_SCREEN, OPEN_PERK_SHOP, ENTER_ARENA, PENDING_REVIVE, REVIVE_CONFIRMED, REVIVE_REJECTED, SHOW_REVIVE_UI, SPAWN_IMPACT_PARTICLE, HIT_STOP}
enum SHAPE_TYPES {CIRCLE, DIAMOND, SQUARE, RECTANGLE, TRIANGLE}

enum ENEMY_STATES {MOVE, ATTACK}

enum TOWER_TYPES {BASE, TURRET, FLAMETHROWER, BURST_SHOOTER, ROCKET_LAUNCHER}
enum ENEMY_TYPES {NORMAL, SNIPER, TANK}
enum ENTITY_TYPES {PLAYER, NORMAL_ENEMY, SNIPER_ENEMY, TANK_ENEMY, BULLET, CELL_HOVER_OVERLAY}

enum COUNTDOWN_ACTIONS {SHOOT, ATTACK}
enum ALIGNMENTS { PLAYER, ENEMY, NEUTRAL }
